using ITSoftware.Models;

namespace ITSoftware.Services
{
    public static partial class PreviousYearQuestionSeeder
    {
        #region 4. Database & SQL
        private static List<PreviousYearQuestion> GetDatabaseQuestions()
        {
            const string cat = "Database & SQL";
            const int order = 4;
            return new List<PreviousYearQuestion>
            {
                // Bangladesh Bank Exams
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] A to B transfer balance but not sent to B? Which property in ACID is responsible?\n(a) Atomicity (b) Consistency (c) Isolation (d) Durability\nAns: (a) Atomicity" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] Which clause is executed first in an SQL query?\n(a) WHERE (b) SELECT (c) FROM (d) ORDER BY\nAns: (c) FROM" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] Which of the following is a DML (Data Manipulation Language) command?\n(a) CREATE (b) DELETE (c) DROP (d) ALTER\nAns: (b) DELETE" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] Which one make data access from a database faster?\n(a) Indexing (b) Normalization (c) Denormalization (d) All of the above\nAns: (a) Indexing" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "A Bank schema is given below:\nBank(Br_Name, Br_City, Assets, Acc_name, Acc_Num, Balance)\n(a) Normalize and point out Primary and Foreign Keys.\n(b) Show that the schema is in good form (1NF, 2NF, 3NF)." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Where is data warehousing used?\n(a) Transaction System (b) Logical system (c) Decision support system (d) None\nAns: (c) Decision support system" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] What is the use of data cleaning?\n(a) To remove the noisy data (b) Transformations to correct the wrong data (c) Correct the inconsistencies in data (d) All of the above\nAns: (d) All of the above" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Small logical units where data warehouse hold large amounts of data is known as:\n(a) Access layers (b) Data marts (c) Data storage (d) Data miners\nAns: (b) Data marts / (d)" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Which of the following is an essential process in which the intelligent methods are applied to extract data patterns?\n(a) Warehousing (b) Data Mining (c) Text Mining (d) Data Selection\nAns: (b) Data Mining" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Which of the following provides the ability to query information from the database and insert tuples into, delete tuples from, and modify tuples in the database?\n(a) DML (Data Manipulation Language) (b) DDL (Data Definition Language) (c) Query (d) Relational Schema\nAns: (a) DML (Data Manipulation Language)" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Programmer", QuestionText = "[MCQ] Table employee has 10 records. It has a non-NULL SALARY column which is also UNIQUE. The SQL statement:\nSELECT COUNT (*) FROM employee\nWHERE SALARY > ALL(SELECT SALARY FROM EMPLOYEE);\nPrints:\n(a) 10 (b) 9 (c) 5 (d) 0\nAns: (d) 0" },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Programmer", QuestionText = "Suppose that we have a relational database with the following tables (underlined are primary keys):\nMovies (mid, title, year)\nPeople (pid, name)\nGenres (gid, genre)\nHasRole (pid, mid, role)\nHasGenre (gid, mid)\nWrite a SQL query to return the number of movies that are romantic comedies." },
                new() { CategoryOrder = order, Category = cat, Year = 2019, ExamOrg = "Bangladesh Bank (BUET)", Post = "Assistant Maintenance Engineer", QuestionText = "Explain the concept of distributed DBMS. What are the features of DBMS?" },
                new() { CategoryOrder = order, Category = cat, Year = 2019, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Programmer", QuestionText = "A company needs a key person for DBMS. What is his/her duty as key person (Database Administrator)?" },
                new() { CategoryOrder = order, Category = cat, Year = 2016, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Repeated data exist at:\n(a) unnormalized (b) 1NF (c) 2NF (d) 3NF\nAns: (a) unnormalized" },
                new() { CategoryOrder = order, Category = cat, Year = 2016, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "Define 'integrity rules' of database systems. Write a SQL query to get the second highest salary from Employee table." },
                new() { CategoryOrder = order, Category = cat, Year = 2016, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "What is cardinality and modality in ER modeling?" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] What is a tuple?\n(a) Another name for a table in an RDBMS (b) A row or record in a database table (c) An attribute attached to a record (d) Another name for the key linking different table in a database\nAns: (b) A row or record in a database table" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] With SQL how can you insert \"Olsen\" as the \"LastName\" in the \"Persons\" table?\n(a) INSERT INTO Persons(LastName) VALUES('Olsen')\n(b) INSERT INTO Persons (Olsen) VALUES('LastName')\n(c) INSERT INTO Person ('Olsen') INTO LastName\n(d) INSERT INTO Persons (LastName= 'Olsen')\nAns: (a)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] The primary key is selected from the:\n(a) Candidate keys (b) Composite keys (c) Determinants (d) Foreign keys\nAns: (a) Candidate keys / (b)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Which SQL keyword is used to sort the result set?\n(a) ORDER (b) SORT (c) ORDER BY (d) SORT BY\nAns: (c) ORDER BY" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] A transaction for which all committed changes are permanent is called:\n(a) Atomic (b) Consistent (c) Isolated (d) Durable\nAns: (d) Durable" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Which of the following locks the item from access of any type?\n(a) Implicit lock (b) Explicit lock (c) Exclusive lock (d) Shared lock\nAns: (c) Exclusive lock" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] In your program you want to use the JDBC-ODBC bridge driver. What code do you use?\n(a) Class.callName(\"sun.jdbc.odbc.JdbcOdbcDriver\")\n(b) Class.forName(\"sun.jdbc.odbc.JdbcOdbcDriver\")\n(c) Class.callFunc(\"JdbcOdbcDriver\")\n(d) Class.Name.init(\"sun.jdbc.odbc.JdbcOdbcDriver\")\nAns: (b) Class.forName(\"sun.jdbc.odbc.JdbcOdbcDriver\")" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] You run a SELECT statement and multiple duplicate values are retrieved. What keyword can you use to retrieve only non-duplicate data?\n(a) DUPLICATE (b) SEPARATE (c) DISTINCT (d) INDEX\nAns: (c) DISTINCT" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Microsoft Access is a:\n(a) RDBMS (b) OODBMS (c) ORDBMS (d) All of these\nAns: (a) RDBMS" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Which of the following is not a type of Microsoft Access Database object?\n(a) Table (b) Form (c) Worksheets (d) Modules\nAns: (c) Worksheets" },

                // Combined & Other Banks
                new() { CategoryOrder = order, Category = cat, Year = 2026, ExamOrg = "BSCS Sonali & Janata Bank", Post = "Assistant Programmer", QuestionText = "EMPLOYEES(ID,Name,DeptID) and DEPARTMENTS(Dept,DeptName). Write pseudo-SQL to get Employee Names who work in \"IT\"." },
                new() { CategoryOrder = order, Category = cat, Year = 2026, ExamOrg = "BSCS Sonali & Janata Bank", Post = "Assistant Programmer", QuestionText = "You are designing a database for a Library. Explain the relationship between a \"Book\" table and a \"Borrower\" table. Is it 1-to-1, 1-to-Many, or Many-to-Many? Justify your answer." },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Combined Bank (BIBM)", Post = "Officer IT", QuestionText = "Sales(sales_id, salesman, region, sale_amount, sale_date). Write SQL to display region, average sale amount, total number of sales for each region where average sale amount > BDT 50,183 and total sales in that region ≥ 5." },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Combined Bank (BIBM)", Post = "Officer IT", QuestionText = "Explain ACID properties in a database transaction: Atomicity, Consistency, Isolation, Durability — how each ensures reliability and integrity." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 5 Bank (BIBM)", Post = "Assistant Programmer", QuestionText = "SQL on Department(DeptCode,DeptName,Location) and Employee(EmpCode,EmpFname,Salary,Commission,DeptCode): (a) Select EmpFname with total salary (salary+commission) (b) Select EmpFname, Location with salary > avg, ordered by EmpFname (c) Select EmpFname and count employees ordered ascending." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 5 Bank (BIBM)", Post = "Assistant Programmer", QuestionText = "Describe different types of relationships in DBMS." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "ADA", QuestionText = "Database Data Loss case study — identify and resolve using appropriate strategy." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "ADA", QuestionText = "Normalize a database, use containers if needed, draw an ERD Diagram for: Proj_Budget, Proj_Code, Proj_Manager, Emp_Code, Emp_Name, Dept_Code, Dept_Name, Salary." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "ADA", QuestionText = "Difference between MS Access and MS FoxPro in SQL or Oracle." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "ADA", QuestionText = "Case study about Database problem solved by ACID Properties." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "ADA", QuestionText = "SQL program to find interest rate from a database: if first two letters of account in the rate table match, assign same rate in EMP table. (EMP table: id, Acc, Name, Salary, AccRate)" },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "Senior Officer IT", QuestionText = "Database has two tables: Customers and Orders. Explain Inner, Left, Right, and Full join. Show result sets. (Customers: 1-Rahim, 2-Karim, 3-Belal, 4-Rony, 5-Helal)" },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "Senior Officer IT", QuestionText = "Briefly describe primary key, foreign key, and index in relational DB. Does database indexing always make applications faster? Explain." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 2 Bank (BIBM)", Post = "Officer IT", QuestionText = "Pet society DB: Animals(ID,Name,PrevOwner,DateAdmitted,Type), Adopter(PSIN,Name,Address,OtherAnimals), Adoption(AnimalID,PSIN,AdoptDate,chipNo). Write SQL to list total adoptions on June 30, 2024 for each animal type." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Combined 5 Bank (BIBM)", Post = "Officer IT", QuestionText = "Relational DB: S(sid,A), T(tid,B), U(uid,C), R(sid,tid,D), Q(tid,uid,E). R = many-to-many S–T, Q = many-to-many T–U. Write SQL query returning all (Sid, uid) records related through R and Q. Use SELECT not SELECT DISTINCT." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Combined Bank (BIBM)", Post = "Officer IT", QuestionText = "Analyze the following SQL code: SELECT department-name, AVG(salary) FROM employees e JOIN department d ON e.department-id=d.department-id WHERE salary > (SELECT AVG(salary) FROM employees) GROUP BY department-name HAVING COUNT(*)>2 ORDER BY average-salary DESC." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Combined 4 Bank (BIBM)", Post = "SO IT", QuestionText = "Difference between database, data warehouse, and data mining with real-world examples." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "RAKUB (BIBM)", Post = "ANSE", QuestionText = "Given a SQL query, write what the question (purpose) of this query is." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Rupali Bank (BIBM)", Post = "ANA", QuestionText = "Analyze output of SQL: SELECT department_name, AVG(salary) FROM employee e JOIN department d … WHERE salary > (SELECT AVG(salary) FROM employee WHERE department_id=d.department_id) GROUP BY department_name HAVING COUNT()>2 ORDER BY average_salary DESC." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "Security Printing Corp Bangladesh", Post = "Sub-Assistant Engineer", QuestionText = "What is DBMS? Write short note on Virtual memory and Cache memory." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ANE JBL", Post = "Assistant Network Engineer", QuestionText = "Create an ER Diagram using: TV channel, reality show, user, producer, user eating." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ANE JBL", Post = "Assistant Network Engineer", QuestionText = "SQL on Actor(actor_id,name,age), Play(play_id,writer), Role(play_id,actor_id). (i) Count actors who played role 3+ times written by \"Shakespeare\". (ii) Show actors who played Chekhov but never Shakespeare." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ANA JBL", Post = "Assistant Network Administrator", QuestionText = "DDL query to create PH_Employee table with reference keys from Employee and City tables. Also write query to get employee_id, last_name, city of employees who reported to someone one or more times." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "SBL/BDBL", Post = "Senior Officer IT", QuestionText = "SQL queries on Worker(worker-id,worker-name,hourly-rate,skill-type,supervisor-id), Assignment(worker-id,building-id,start-date,num-days), Building(building-id,address,building-type): (a) Skill types of workers assigned to B02 (b) Workers assigned to warehouse buildings (c) No. of workers per building where >5 workers (d) Give 5% hourly wage increment to workers in hospital buildings." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "Draw an ER diagram of BPL (Team, Player, Game, Captain)." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "What is a trigger? When is it used? Write down some advantages of triggers." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "Write short notes on ACID properties of a database." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "What is a distributed database system? What are the responsibilities of a database administrator?" },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "MARKS(id, mark) table: write query to show grades (F,A,C etc.) according to marks, and another query to show number of students who got a particular grade." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "BCNF related question (normalize a relation to BCNF)." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "Weak entity type vs. strong entity type — show example in an ER diagram." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ANE RBL", Post = "Assistant Network Engineer", QuestionText = "Draw an ER diagram for a football club: name, stadium, team of players (one club each), manager (buys players), matches (each club plays every other, date/venue/score)." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ANE RBL", Post = "Assistant Network Engineer", QuestionText = "SQL on Employee(employee_id, name, salary, department), Leave(employee_id, date, reason), Holiday(date, description). (i) Mapping cardinality between Employee and Holiday. (ii) Query to show all employees' leave count." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "Security Printing Corp Bangladesh", Post = "Assistant Maintenance Engineer", QuestionText = "DBMS definition and why normalization in database?" },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "Security Printing Corp Bangladesh", Post = "Assistant Maintenance Engineer", QuestionText = "Define primary key, foreign key, and unique key." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "BSCA Sonali Bank", Post = "Officer IT", QuestionText = "Comparison and Contrast between SQL and NoSQL Database." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "BSCA Sonali Bank", Post = "Officer IT", QuestionText = "Draw an E-R Diagram for a Railway Reservation System with passengers, Terminal, Train, Seat schemas and different attributes." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "BSCA Sonali Bank", Post = "Officer IT", QuestionText = "Write a query to find the publisher name which location is 'Dhaka' and which book is published after 1980." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "BSCA Sonali Bank", Post = "Officer IT", QuestionText = "Write a query to change the type of Book name 'Science' to 'Computer Science' which branch name is 'Dhaka' city." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "SQL: Employee(Empid,Lastname,Firstname,street,city), Works(Empid,deptName,company,salary), Manager(manid,name,deptName). (i) Number of employees in each department. (ii) Give 15% salary increase to employees with salary > 20,000." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "AHE SBL/JBL/RBL", Post = "Assistant Hardware Engineer", QuestionText = "Convert the given ER diagram (Lot, ProductionUnits, RawMaterials) into a relational database schema maintaining primary keys properly." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "BSCS Combined 2 Bank (SB&JB)", Post = "Officer IT", QuestionText = "A transaction consists of a sequence of query/update statements. List SQL statements required to end a transaction and write their functions." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "BSCS Combined 2 Bank (SB&JB)", Post = "Officer IT", QuestionText = "Main components of SQL are DDL, DML, and DCL. Give examples of DDL, DML, and DCL commands." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "Combined 3 Banks (SBL/BDBL)", Post = "Senior Officer IT", QuestionText = "When does a Deadlock occur and how do you prevent it in a database?" },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "Combined 3 Banks (SBL/BDBL)", Post = "Senior Officer IT", QuestionText = "Classify the failure of Database Management." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "ANE JBL", Post = "Assistant Network Engineer", QuestionText = "Design an ER diagram for a soccer club application capturing: Teams (ID, name, stadium, city), Players (number, name, DOB, start year, shirt number), Matches (host/guest, date, result), Player stats (goals, yellow/red cards). Ensure cardinalities and primary keys are clear." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "ANE JBL", Post = "Assistant Network Engineer", QuestionText = "SQL queries on tables: Employee(emp_id, emp_name, street, emp_city, join_date), Works(emp_id, comp_name, leaves, salary, dept, man_id), Company(comp_id, comp_name, comp_city), Manager(man_id, emp_id, man_name). (i) Employees with salary between 5000–8000 (ii) Employees earning more than department average (iii) Leave count per employee (iv) Managers and employee counts." },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "Combined 3 Banks (SBL/JBL/Rakub)", Post = "SO Written", QuestionText = "SQL queries on Employees(ename,street,city), Works(ename,cname,salary,joindate), Company(cname,city), Manages(ename,mname): (i) Name/street/city working for \"First Corporation Bank\" earning >3000 (ii) Employees living in same city as their company (iii) Give First Corporation Bank employees 10% raise (iv) Companies with payroll < 100,000" },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "ADA SBL", Post = "Assistant Database Admin", QuestionText = "Design an ER diagram for a soccer club with teams, players, matches, substitutions, and exactly three referees per match (one main, two assistant). Include substitution time, referee details (ID, name, DOB, experience). Cardinalities and PKs must be clear." }
            };
        }
        #endregion
    }
}

