using ITSoftware.Models;

namespace ITSoftware.Services
{
    public static partial class PreviousYearQuestionSeeder
    {
        #region 8. Operating Systems
        private static List<PreviousYearQuestion> GetOperatingSystemsQuestions()
        {
            const string cat = "Operating Systems";
            const int order = 8;
            return new List<PreviousYearQuestion>
            {
                // Bangladesh Bank Exams
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] A process needs I/O operations, it switches to:\n(a) Ready (b) Running (c) Waiting (Blocked) (d) Terminated\nAns: (c) Waiting (Blocked)" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "[MCQ] Priority Scheduling (Non-Preemptive) with No Arrival Time. Consider processes:\nP1 (BT: 10, Priority: 3), P2 (BT: 1, Priority: 1), P3 (BT: 2, Priority: 4), P4 (BT: 1, Priority: 5), P5 (BT: 5, Priority: 2).\nUsing Non-Preemptive Priority Scheduling (lower number = higher priority), what is the Average Turnaround Time (TAT)?\n(a) 10 (b) 8.6 (c) 12 (d) 9.2\nAns: (c) 12" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Bangladesh Bank (DU)", Post = "Assistant Director (ICT)", QuestionText = "Banker's Algorithm: 5 processes P0 through P4; 3 resource types A (10 instances), B (5 instances), and C (7 instances).\nAllocation and Max matrices given.\n(a) Calculate the Need matrix.\n(b) Determine whether the system is in a Safe state or Unsafe state and write the safe sequence." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Bangladesh Bank (BIBM)", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Page fault occurs when:\n(a) When a requested page is in memory (b) When a requested page is not in memory (c) When a page is corrupted (d) When an exception is thrown\nAns: (b) When a requested page is not in memory" },
                new() { CategoryOrder = order, Category = cat, Year = 2019, ExamOrg = "Bangladesh Bank (BUET)", Post = "Assistant Maintenance Engineer", QuestionText = "What is the difference between micro kernel and macro (monolithic) kernel? What are the sub-components of I/O manager in Windows NT?" },
                new() { CategoryOrder = order, Category = cat, Year = 2016, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "Define system software and application software with three examples of each." },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] A page fault occurs:\n(a) When the page is not in the memory (b) When the page is in the memory (c) When the process enters into the blocked state (d) When the process is in the ready state\nAns: (a)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Multiprogramming systems:\n(a) Are easier to develop than single programming system (b) Execute each job faster (c) Execute more jobs in the same time (d) Are used only on large mainframe computers\nAns: (c) Execute more jobs in the same time" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] Which of the following file name extensions suggests that the file is backup of another file?\n(a) .TXT (b) .COM (c) .BAS (d) .BAK\nAns: (d) .BAK" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "[MCQ] \"INI\" extension usually refers to what kind of file?\n(a) Image file (b) System file (c) Hypertext file (d) Image Color Matching Profile file\nAns: (b) System file" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Maintenance Engineer", QuestionText = "What is turnaround time of a process? What is the difference between FAT32 and NTFS file systems?" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] What is entered by the Excel function =today()?\n(a) The date value for the day according to system clock (b) The time value according to system clock (c) Today's date as text format (d) All of the above\nAns: (a)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] Where can you find the horizontal split bar on MS Word screen?\n(a) On the left of horizontal scroll bar (b) On the right of horizontal scroll bar (c) On the top of vertical scroll bar (d) On the bottom of vertical scroll bar\nAns: (c) On the top of vertical scroll bar" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] What happens when you press Ctrl+X after selecting some cells in Excel?\n(a) The cell content disappears and stored in clipboard (b) The cells selected are marked for cutting (c) The selected cells are deleted (d) None\nAns: (b)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] You cannot close MS Word application by:\n(a) Choosing File Menu and then exit Sub Menu (b) From File Menu choose close Sub Menu (c) Click X button on title bar (d) Press Alt+F4\nAns: (b)" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] What program do you use to create a spreadsheet?\n(a) Word (b) Excel (c) Access (d) PowerPoint\nAns: (b) Excel" },
                new() { CategoryOrder = order, Category = cat, Year = 2011, ExamOrg = "Bangladesh Bank", Post = "Assistant Programmer", QuestionText = "[MCQ] What is the term used when you press and hold the left mouse key and move the mouse round the slide?\n(a) Highlighting (b) Dragging (c) Selecting (d) Moving\nAns: (b) Dragging" },

                // Combined & Other Banks
                new() { CategoryOrder = order, Category = cat, Year = 2026, ExamOrg = "BSCS Sonali & Janata Bank", Post = "Assistant Programmer", QuestionText = "Explain the fundamental difference between a Process and a Thread. Provide two distinct advantages of using threads over processes." },
                new() { CategoryOrder = order, Category = cat, Year = 2026, ExamOrg = "BSCS Sonali & Janata Bank", Post = "Assistant Programmer", QuestionText = "Explain the \"Producer-Consumer\" problem in operating systems. What specific synchronization issue must be solved?" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Combined Bank (BIBM)", Post = "Officer IT", QuestionText = "Logical address space of 512 pages, 2-KB page size, mapped onto 128 frames. (a) Bits required in logical address? (b) Bits required in physical address?" },
                new() { CategoryOrder = order, Category = cat, Year = 2025, ExamOrg = "Combined Bank (BIBM)", Post = "Officer IT", QuestionText = "Explain the concept of thrashing in an OS: how it occurs in a demand-paged virtual memory system and how it impacts CPU utilization and system performance." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 3 Bank (BIBM)", Post = "AME/AE IT", QuestionText = "Define: socket, kernel, process, program, multiprogramming, context switching. Discuss LRU and NRU Page Replacement Algorithms. Illustrate Preemptive Priority scheduling." },
                new() { CategoryOrder = order, Category = cat, Year = 2024, ExamOrg = "Combined 2 Bank (BIBM)", Post = "Officer IT", QuestionText = "Give the necessary condition for deadlock. Is it possible to have deadlock involving only a single process? Explain." },
                new() { CategoryOrder = order, Category = cat, Year = 2023, ExamOrg = "Combined Bank (BIBM)", Post = "Senior Officer AHE/AME", QuestionText = "Differentiate between physical memory and virtual memory; also describe advantages and disadvantages of virtual memory." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "Security Printing Corp Bangladesh", Post = "Sub-Assistant Engineer", QuestionText = "What is kernel? Write down objectives of kernel." },
                new() { CategoryOrder = order, Category = cat, Year = 2022, ExamOrg = "ADA SBL/JBL", Post = "Assistant Database Administrator", QuestionText = "UNIX CLI: how to show hidden files in a directory." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ANE RBL", Post = "Assistant Network Engineer", QuestionText = "Processes: A(arr=0,exec=10), B(arr=3,exec=7), C(arr=5,exec=3), D(arr=8,exec=5). Find average waiting time for FCFS, Preemptive SJF, and Round Robin (quantum=3)." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "What is Deadlock? Explain two deadlock situations with system resources." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "A system has 4 periodic events with periods 50,100,200,250 ms requiring 35,20,10,x ms of CPU. What is the largest value of x for which the system is schedulable?" },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "5 processes: A(arr=3,exec=1), B(arr=1,exec=4), C(arr=4,exec=2), D(arr=0,exec=6), E(arr=2,exec=3). CPU scheduling is SJF. Calculate average waiting time." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "Shell script: (i) Create folder \"A\" with read-only permission. (ii) Copy contents of folder \"P\" to a directory of a subfolder with the same name as the current folder." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "ASA JBL", Post = "Assistant System Administrator", QuestionText = "Memory partitions: 100,500,200,300,600 KB. First-fit and best-fit for processes 212,417,112,426 KB. Which algorithm makes most efficient use of memory?" },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "AHE SBL/JBL/RBL", Post = "Assistant Hardware Engineer", QuestionText = "CPU scheduling Round Robin (quantum=3): given arrival and burst times. Calculate average waiting time." },
                new() { CategoryOrder = order, Category = cat, Year = 2021, ExamOrg = "AHE SBL/JBL/RBL", Post = "Assistant Hardware Engineer", QuestionText = "How do swapping and virtual memory help in memory management system?" },
                new() { CategoryOrder = order, Category = cat, Year = 2020, ExamOrg = "BSCS Combined 2 Bank (SB&JB)", Post = "Officer IT", QuestionText = "List and briefly define the major types of OS scheduling (OS scheduling is the key concept of multiprogramming)." }
            };
        }
        #endregion
    }
}

